version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: TodoApplicationDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234!
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"